version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - '${PG_PORT}:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
